apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-deployment
  labels:
    app: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      terminationGracePeriodSeconds: 30    
      containers:
      - name: simpleapp-container
        image: mfarhan1998/simpleapp:1.0
        imagePullPolicy: "Always"        
        ports:
        - containerPort: 8080

